server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  
spring: 
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true 
 
swagger: 
   enabled: true
dubbo:  
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: consumer
      owner: wuj
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
      check: false
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受（订阅）。 
      name: dubbo
      port: 20880
    annotation:
      package: com.bosssoft.platform.bpmnx.api