jdbc: 
   databaseSchema: ASSET_SMART
bpmnx: 
  spi: 
   omservice: com.bosssoft.egov.asset.activiti.user.MockOMServiceImpl
swagger: 
   enabled: true
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
server: 
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  
spring: 
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true 
 # ====================druid====================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@//192.168.10.180:1521/orcl
    #username: egams_qzss
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    username: asset_smart
    password: bs
    druid: 
      #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 1
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      #验证连接有效与否的SQL，不同的数据配置不同
      validation-query: select 'x' from dual
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
      #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      #这里建议配置为TRUE，防止取到的连接不可用
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #常用的插件有： 监控统计用的filter:stat,日志用的filter:log4j,防御sql注入的filter:wall
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
      #超过时间限制是否回收
      remove-abandoned: true
      #超过时间限制多长
      remove-abandoned-timeout: 1800 
    
  
    
# ====================MybatisPlus====================
mybatisPlus:
  #typeEnumsPackage: com.wiesel.common.enums
  #typeHandlersPackage : com.wiesel.common.enums.handler
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.bosssoft.**.entity
  globalConfig:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    idType: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    fieldStrategy: 2
    #驼峰下划线转换
    dbColumnUnderline: true
    #刷新mapper 调试神器
    refreshMapper: true
    #数据库大写下划线转换
    capital-mode: true
    #逻辑删除配置
    logicDeleteValue: 0
    logicNotDeleteValue: 1
  configuration:
    map-underscore-to-camel-case: true
    #全局的映射器启用或禁用缓存 
    cache-enabled: false
    #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载 
    lazyLoadingEnabled: false
    aggressive-lazy-loading: true
    default-statement-timeout: 25000
    defaultExecutorType: REUSE
    useColumnLabel: true
    #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multipleResultSetsEnabled: true  