jdbc: 
   databaseSchema: ASSET_SMART
bpmnx: 
  spi: 
   omservice: cn.com.bosssoft.egov.asset.activiti.user.MockOMServiceImpl
logging: 
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
